# Generated by Django 3.1.2 on 2020-10-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201017_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(default=12353, max_length=200),
            preserve_default=False,
        ),
    ]
