# Generated by Django 3.1.2 on 2020-10-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vote_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='votes',
        ),
    ]
