# Generated by Django 2.1.5 on 2020-10-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='theme',
            field=models.ManyToManyField(default=None, to='main.Theme'),
        ),
    ]
