# Generated by Django 2.1.5 on 2020-10-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201020_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_seq',
            field=models.CharField(default='004416', max_length=200),
            preserve_default=False,
        ),
    ]
