# Generated by Django 2.2.14 on 2020-10-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201020_2138'),
        ('main', '0004_remove_vote_votes'),
        ('main', '0003_movie_poster'),
    ]

    operations = [
    ]
