# Generated by Django 2.1.5 on 2020-10-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_vote_votes'),
        ('main', '0003_movie_poster'),
        ('main', '0007_like'),
    ]

    operations = [
    ]
