# Generated by Django 2.1.5 on 2020-10-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20201021_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='num_like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='theme',
            field=models.ManyToManyField(to='main.Theme'),
        ),
    ]
