# Generated by Django 2.2.14 on 2020-10-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201021_2235'),
        ('main', '0007_merge_20201021_1630'),
    ]

    operations = [
    ]
