# Generated by Django 2.2.14 on 2020-10-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20201022_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='theme',
            field=models.ManyToManyField(default=None, to='main.Theme'),
        ),
    ]
