# Generated by Django 2.1.5 on 2020-10-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20201022_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='votemovie',
            name='vote_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='theme',
            field=models.ManyToManyField(default=None, to='main.Theme'),
        ),
    ]
