# Generated by Django 2.2.14 on 2020-10-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201023_1059'),
        ('main', '0011_auto_20201022_1947'),
    ]

    operations = [
    ]
