# Generated by Django 2.2.14 on 2020-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_merge_20201023_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='theme',
            name='subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
