# Generated by Django 2.2.14 on 2020-10-24 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201023_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='movie',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.VoteMovie'),
        ),
    ]
