# Generated by Django 2.2.14 on 2020-10-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201024_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='theme',
        ),
    ]
